### ISSUE TITLE
Hi, I am very interested in your paper and would like to run your program. But I found that there seems to be a missing eva_clip.py file, could you please publish this eva_clip.py file?

### ISSUE THREAD

**Issue by xuguangyi1999** [HJYao00/Side4Video#3]
Hi, I am very interested in your paper and would like to run your program. But I found that there seems to be a missing eva_clip.py file, could you please publish this eva_clip.py file?

**Comment by HJYao00** [comment]
Hello, I am still organizing the code in this regard. I will update it in the next few days.

**Comment by xuguangyi1999** [comment]
Thank you!

**Comment by HJYao00** [comment]
I have uploaded the relevant code.
