### ISSUE TITLE
Side4Video Blocks

### ISSUE THREAD

**Issue by shuguang-52** [HJYao00/Side4Video#5]
I've been equally focused on efficient image-to-video learning lately, and I thank the authors for open-sourcing their excellent work. However, I don't find the side4video block in the code, there is no relevant code inside the video clip. 

Did the author give them different names in the code?

**Comment by HJYao00** [comment]
Please check the code here: https://github.com/HJYao00/Side4Video/blob/main/Recognition/clip/model.py#L400
